### ISSUE TITLE
failed test when run on windows

### ISSUE THREAD

**Issue by aqyuki** [JY8752/note-cli#8]
## description

When I running `go test ./...`, I got panic

This is probably due to the fact that directory delimiters are represented by ` \ ` ɑ in Windows environments, whereas they are represented by `/` in Mac and Linux environments.

**Comment by JY8752** [comment]
@aqyuki 
The panic occurs when you run test in the local environment, right?
Can you please post a log of when you panic?

**Comment by aqyuki** [comment]
```txt
?       github.com/JY8752/note-cli      [no test files]
?       github.com/JY8752/note-cli/internal/clock       [no test files]
Error: if any flags in the group [time name] are set none of the others can be; [name time] were all set
Error: if any flags in the group [time name] are set none of the others can be; [name time] were all set
Error: if any flags in the group [time name] are set none of the others can be; [name time] were all set
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 7 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0000a4500, 0xc000114320)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:855 +0x105
github.com/spf13/cobra.(*Command).LocalFlags.func1(0xc000114320)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1636 +0xc5
github.com/spf13/pflag.(*FlagSet).VisitAll(0x13ddf80?, 0xc0001aab30)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0xd8
github.com/spf13/cobra.(*Command).LocalFlags(0x13ddf80)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1639 +0x1a9
github.com/spf13/cobra.(*Command).HasAvailableLocalFlags(0x1?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1734 +0x13
reflect.Value.call({0xdc9860?, 0x13ddf80?, 0x8fd9a5?}, {0xdcc158, 0x4}, {0x143da40, 0x0, 0x7dc26f?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0xdc9860?, 0x13ddf80?, 0xc00023c050?}, {0x143da40?, 0x13?, 0x27?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/reflect/value.go:380 +0xb9
text/template.safeCall({0xdc9860?, 0x13ddf80?, 0x13ddf80?}, {0x143da40?, 0xc0001ab4b0?, 0x7ef1d6?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/funcs.go:367 +0x8c
text/template.(*state).evalCall(0xc0001abcc0, {0xdc9860?, 0x13ddf80?, 0x0?}, {0xdc9860?, 0x13ddf80?, 0xc00008e218?}, 0x0, {0xff4760, 0xc00019bb60}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:803 +0x85b
text/template.(*state).evalField(0xc0001abcc0, {0xdc9860?, 0x13ddf80?, 0xdaffe0?}, {0xe018c9, 0x16}, {0xff4760, 0xc00019bb60}, {0xc000035720, 0x1, ...}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:652 +0x9a8
text/template.(*state).evalFieldChain(0x0?, {0xdc9860?, 0x13ddf80?, 0xcb4fa0?}, {0xdc9860?, 0x13ddf80?, 0x8?}, {0xff4760, 0xc00019bb60}, {0xc000035710, ...}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:613 +0x1d4
text/template.(*state).evalFieldNode(...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:577
text/template.(*state).evalCommand(0xc0001abcc0, {0xdc9860?, 0x13ddf80?, 0x0?}, 0xff4640?, {0xcf57a0?, 0x143da40?, 0xc00019a180?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:505 +0x12a
text/template.(*state).evalPipeline(0xc0001abcc0, {0xdc9860?, 0x13ddf80?, 0x753729?}, 0xc00006f320)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:479 +0x125
text/template.(*state).walkIfOrWith(0xc0001abcc0, 0xa, {0xdc9860?, 0x13ddf80?, 0xd0?}, 0xd67040?, 0x1?, 0x0)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:301 +0xc5
text/template.(*state).walk(0xc0001abcc0, {0xdc9860?, 0x13ddf80?, 0x30?}, {0xff45b0?, 0xc000037bc0?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:277 +0x14d
text/template.(*state).walk(0xc0001abcc0, {0xdc9860?, 0x13ddf80?, 0xc000126b40?}, {0xff4448?, 0xc00019a180?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:280 +0x2aa
text/template.(*Template).execute(0xc000037100, {0xfede20?, 0xc00019a060?}, {0xdc9860?, 0x13ddf80?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:224 +0x278
text/template.(*Template).Execute(...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:207
github.com/spf13/cobra.tmpl({0xfede20, 0xc00019a060}, {0xe0155c, 0x566}, {0xdc9860, 0x13ddf80})
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/cobra.go:179 +0x165
github.com/spf13/cobra.(*Command).UsageFunc.func1(0xd55360?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:422 +0x69
github.com/spf13/cobra.(*Command).Usage(0xc10a19?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:434 +0x25
github.com/spf13/cobra.(*Command).UsageString(0x13ddf80)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:475 +0xc5
github.com/spf13/cobra.(*Command).ExecuteC(0x13de820)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1086 +0x4a5
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/JY8752/note-cli/cmd.TestCommandFlag.func1(0xc000190000)
        C:/Users/K.Yosuke/GolandProjects/note-cli-fork/cmd/root_test.go:37 +0x7a
testing.tRunner(0xc000190000, 0xc000036f80)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 6
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1648 +0x3ad

goroutine 1 [chan receive]:
testing.tRunner.func1()
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1561 +0x489
testing.tRunner(0xc000055a00, 0xc000143c48)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1601 +0x138
testing.runTests(0xc000114640?, {0x13d11b0, 0x1, 0x1}, {0x717525?, 0xc000143d08?, 0x13e7660?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:2052 +0x445
testing.(*M).Run(0xc000114640)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1925 +0x636
main.main()
        _testmain.go:47 +0x19c

goroutine 6 [chan receive]:
testing.tRunner.func1()
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1561 +0x489
testing.tRunner(0xc000055ba0, 0xf5dba0)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1601 +0x138
created by testing.(*T).Run in goroutine 1
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1648 +0x3ad

goroutine 8 [running]:
        goroutine running on other thread; stack unavailable
created by testing.(*T).Run in goroutine 6
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1648 +0x3ad

goroutine 9 [runnable]:
github.com/spf13/pflag.(*FlagSet).normalizeFlagName(0xc00017e200?, {0xdcc01c?, 0x4?})
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:253 +0x4e
github.com/spf13/pflag.(*FlagSet).Lookup(...)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:349
github.com/spf13/cobra.(*Command).LocalFlags.func1(0xc000114320)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1635 +0x85
github.com/spf13/pflag.(*FlagSet).VisitAll(0x13ddf80?, 0xc0000c8b30)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0xd8
github.com/spf13/cobra.(*Command).LocalFlags(0x13ddf80)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1639 +0x1a9
github.com/spf13/cobra.(*Command).HasAvailableLocalFlags(0x1?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1734 +0x13
reflect.Value.call({0xdc9860?, 0x13ddf80?, 0x8fd9a5?}, {0xdcc158, 0x4}, {0x143da40, 0x0, 0x7dc26f?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0xdc9860?, 0x13ddf80?, 0xc00023c050?}, {0x143da40?, 0x13?, 0x27?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/reflect/value.go:380 +0xb9
text/template.safeCall({0xdc9860?, 0x13ddf80?, 0x13ddf80?}, {0x143da40?, 0xc0000c94b0?, 0x7ef1d6?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/funcs.go:367 +0x8c
text/template.(*state).evalCall(0xc0000c9cc0, {0xdc9860?, 0x13ddf80?, 0x0?}, {0xdc9860?, 0x13ddf80?, 0xc00000ae90?}, 0x0, {0xff4760, 0xc0000a7d40}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:803 +0x85b
text/template.(*state).evalField(0xc0000c9cc0, {0xdc9860?, 0x13ddf80?, 0xdaffe0?}, {0xe018c9, 0x16}, {0xff4760, 0xc0000a7d40}, {0xc000086770, 0x1, ...}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:652 +0x9a8
text/template.(*state).evalFieldChain(0x0?, {0xdc9860?, 0x13ddf80?, 0xcb4fa0?}, {0xdc9860?, 0x13ddf80?, 0x8?}, {0xff4760, 0xc0000a7d40}, {0xc000086760, ...}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:613 +0x1d4
text/template.(*state).evalFieldNode(...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:577
text/template.(*state).evalCommand(0xc0000c9cc0, {0xdc9860?, 0x13ddf80?, 0x0?}, 0xff4640?, {0xcf57a0?, 0x143da40?, 0xc0000a6360?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:505 +0x12a
text/template.(*state).evalPipeline(0xc0000c9cc0, {0xdc9860?, 0x13ddf80?, 0x753729?}, 0xc0000bef00)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:479 +0x125
text/template.(*state).walkIfOrWith(0xc0000c9cc0, 0xa, {0xdc9860?, 0x13ddf80?, 0xd0?}, 0xd67040?, 0x1?, 0x0)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:301 +0xc5
text/template.(*state).walk(0xc0000c9cc0, {0xdc9860?, 0x13ddf80?, 0x30?}, {0xff45b0?, 0xc00009ebc0?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:277 +0x14d
text/template.(*state).walk(0xc0000c9cc0, {0xdc9860?, 0x13ddf80?, 0xc0000ba120?}, {0xff4448?, 0xc0000a6360?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:280 +0x2aa
text/template.(*Template).execute(0xc00009e100, {0xfede20?, 0xc0000a6240?}, {0xdc9860?, 0x13ddf80?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:224 +0x278
text/template.(*Template).Execute(...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:207
github.com/spf13/cobra.tmpl({0xfede20, 0xc0000a6240}, {0xe0155c, 0x566}, {0xdc9860, 0x13ddf80})
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/cobra.go:179 +0x165
github.com/spf13/cobra.(*Command).UsageFunc.func1(0xd55360?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:422 +0x69
github.com/spf13/cobra.(*Command).Usage(0xc10a19?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:434 +0x25
github.com/spf13/cobra.(*Command).UsageString(0x13ddf80)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:475 +0xc5
github.com/spf13/cobra.(*Command).ExecuteC(0x13de820)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1086 +0x4a5
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/JY8752/note-cli/cmd.TestCommandFlag.func1(0xc000190680)
        C:/Users/K.Yosuke/GolandProjects/note-cli-fork/cmd/root_test.go:37 +0x7a
testing.tRunner(0xc000190680, 0xc000037000)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 6
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1648 +0x3ad

goroutine 8 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0000a4500, 0xc000114320)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:855 +0x105
github.com/spf13/cobra.(*Command).LocalFlags.func1(0xc000114320)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1636 +0xc5
github.com/spf13/pflag.(*FlagSet).VisitAll(0x13ddf80?, 0xc00024eb30)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0xd8
github.com/spf13/cobra.(*Command).LocalFlags(0x13ddf80)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1639 +0x1a9
github.com/spf13/cobra.(*Command).HasAvailableLocalFlags(0x1?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1734 +0x13
reflect.Value.call({0xdc9860?, 0x13ddf80?, 0x8fd9a5?}, {0xdcc158, 0x4}, {0x143da40, 0x0, 0x7dc26f?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0xdc9860?, 0x13ddf80?, 0xc00023c050?}, {0x143da40?, 0x13?, 0x27?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/reflect/value.go:380 +0xb9
text/template.safeCall({0xdc9860?, 0x13ddf80?, 0x13ddf80?}, {0x143da40?, 0xc00024f4b0?, 0x7ef1d6?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/funcs.go:367 +0x8c
text/template.(*state).evalCall(0xc00024fcc0, {0xdc9860?, 0x13ddf80?, 0x0?}, {0xdc9860?, 0x13ddf80?, 0xc00020e1c8?}, 0x0, {0xff4760, 0xc000223d40}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:803 +0x85b
text/template.(*state).evalField(0xc00024fcc0, {0xdc9860?, 0x13ddf80?, 0xdaffe0?}, {0xe018c9, 0x16}, {0xff4760, 0xc000223d40}, {0xc000206760, 0x1, ...}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:652 +0x9a8
text/template.(*state).evalFieldChain(0x0?, {0xdc9860?, 0x13ddf80?, 0xcb4fa0?}, {0xdc9860?, 0x13ddf80?, 0x8?}, {0xff4760, 0xc000223d40}, {0xc000206750, ...}, ...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:613 +0x1d4
text/template.(*state).evalFieldNode(...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:577
text/template.(*state).evalCommand(0xc00024fcc0, {0xdc9860?, 0x13ddf80?, 0x0?}, 0xff4640?, {0xcf57a0?, 0x143da40?, 0xc000222360?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:505 +0x12a
text/template.(*state).evalPipeline(0xc00024fcc0, {0xdc9860?, 0x13ddf80?, 0x753729?}, 0xc000244f00)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:479 +0x125
text/template.(*state).walkIfOrWith(0xc00024fcc0, 0xa, {0xdc9860?, 0x13ddf80?, 0xd0?}, 0xd67040?, 0x1?, 0x0)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:301 +0xc5
text/template.(*state).walk(0xc00024fcc0, {0xdc9860?, 0x13ddf80?, 0x30?}, {0xff45b0?, 0xc000230b80?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:277 +0x14d
text/template.(*state).walk(0xc00024fcc0, {0xdc9860?, 0x13ddf80?, 0xc000240120?}, {0xff4448?, 0xc000222360?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:280 +0x2aa
text/template.(*Template).execute(0xc0002300c0, {0xfede20?, 0xc000222240?}, {0xdc9860?, 0x13ddf80?})
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:224 +0x278
text/template.(*Template).Execute(...)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/text/template/exec.go:207
github.com/spf13/cobra.tmpl({0xfede20, 0xc000222240}, {0xe0155c, 0x566}, {0xdc9860, 0x13ddf80})
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/cobra.go:179 +0x165
github.com/spf13/cobra.(*Command).UsageFunc.func1(0xd55360?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:422 +0x69
github.com/spf13/cobra.(*Command).Usage(0xc10a19?)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:434 +0x25
github.com/spf13/cobra.(*Command).UsageString(0x13ddf80)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:475 +0xc5
github.com/spf13/cobra.(*Command).ExecuteC(0x13de820)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1086 +0x4a5
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/K.Yosuke/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/JY8752/note-cli/cmd.TestCommandFlag.func1(0xc000190340)
        C:/Users/K.Yosuke/GolandProjects/note-cli-fork/cmd/root_test.go:37 +0x7a
testing.tRunner(0xc000190340, 0xc000036fc0)
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 6
        C:/Users/K.Yosuke/scoop/apps/go/current/src/testing/testing.go:1648 +0x3ad
FAIL    github.com/JY8752/note-cli/cmd  0.475s
--- FAIL: TestExist (2.00s)
    testing.go:1225: TempDir RemoveAll cleanup: remove C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestExist1296777787\001\dir\test.txt: The process cannot access the file because it is being used by another process.
FAIL
FAIL    github.com/JY8752/note-cli/internal/file        2.155s
Create directory. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\test
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\test\test.md
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\test\config.yaml
Create directory. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\article
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\article\article.md
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\article\config.yaml
Create directory. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\2023-09-09
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\2023-09-09\2023-09-09.md
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\2023-09-09\config.yaml
Create directory. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\article2
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\article2\article2.md
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\article2\config.yaml
Create directory. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\2023-09-10-2
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\2023-09-10-2\2023-09-10-2.md
Create file. C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\2023-09-10-2\config.yaml
--- FAIL: TestCreateArticleFunc (1.82s)
    testing.go:1225: TempDir RemoveAll cleanup: remove C:\Users\KD0A0~1.YOS\AppData\Local\Temp\TestCreateArticleFunc2554445602\001\2023-09-09\2023-09-09.md: The process cannot access the file because it is being used by another process.
FAIL
FAIL    github.com/JY8752/note-cli/internal/run 2.061s
FAIL
```

**Comment by aqyuki** [comment]
I was able to solve the problem on my own.
Looks like it was failing due to a change in the root function.

**Comment by JY8752** [comment]
@aqyuki 
Perhaps you are getting an error trying to delete a file that is still open.
Please confirm that I have addressed this so that the test will pass in a Windows environment. This issue is closed, but if you still have problems, please reopen it.
